language: node_js
node_js:
- '12'
install:
- cd $TRAVIS_BUILD_DIR/backend
- npm install
- cd $TRAVIS_BUILD_DIR/authService
- npm install
before_script:
- cd $TRAVIS_BUILD_DIR
script:
- sh scripts/run-tests.sh
before_deploy:
- cd $TRAVIS_BUILD_DIR/backend
deploy:
  - provider: heroku
    api_key:
      secure: VrMEQiekyY2vU27ZI4Q2534d+r8IBGToKv1K0RJz+QYin29vaHDZ4mx+ymZ43kl8WGTC8cLYBK2XZo8i+0BJU4lrmaYqytx1L03UPX22ABC82QwAee95FZV/lBC+aUlR8luDY2XNbUVnvmSIcajdrrYOTLZ1jsFtQoAJaAG+1B5o7vtqB6aBdL2ax22YL16ZpxScx/jjyaxM/qLxukSR20xMIuAo10zDCCAdWf9ZLs6eO+PdLdJXQi+6a4mMQEnue0bACD2VIzSegqoa79TjbjNa0x/KRkUWxEouC13uSQ7cCL5the5YT+yMimTp76zXE5+CbF849HIkQvCnB+tiV4/a4UP1nLX+neP0gDwuzeY7GbMBxTrOSLEOCoVbmNBrSajb3GJIQHzyENYqgpRzY2oTVor6U79Q5Qnc3Cs/LNP+GmVVnDWNiiT22u9w70WJ5Oe4jlfLlB3NxLSoPIFlOZKWtVFeuG3m4p8FDTIplhV8H5HHdN2Qcf9+isnsJhNAS2k0v8GAnx/wKa0Jr65Un5PU4jpq3bq43RfgbCOSWo1Z0JwNpvAHSYMuzzskDu3aasN1C2qEIlfHPcwugmwOwCAK55gbTs4CaDJSbCZxlNGFnR3Hosgcj+e8QhvIikTXlBFDl1xtkPJLeJBQ6y2LTyekhHmZ660KRTRtB0eH08I=
    app: via-fam
